#!/usr/bin/env bash
#
# nginx-callback-proxy-hook.sh
#
# Example helper for mcp-remote's --pre-listen-hook / --post-auth-hook.
#
# It writes (and later removes) an nginx snippet that forwards the OAuth
# callback URL to mcp-remote's local listener for the duration of a single
# authorization flow.
#
# ─── Setup (one time) ────────────────────────────────────────────────────────
#
# Pick a directory that your nginx server block already `include`s. A common
# pattern is to add this line inside the `server { ... }` block that handles
# your public hostname:
#
#     include /etc/nginx/snippets/mcp-remote-*.conf;
#
# Make sure the user that runs mcp-remote can write to that directory and run
# `nginx -s reload` (e.g. via a narrowly-scoped sudoers entry). Both can be
# overridden via NGINX_SNIPPET_DIR and NGINX_RELOAD env vars below.
#
# ─── Usage in your MCP client config ─────────────────────────────────────────
#
#     "args": [
#       "mcp-remote",
#       "https://remote.mcp.server/sse",
#       "3334",
#       "--host", "my-domain.com",
#       "--callback-port", "443",
#       "--callback-scheme", "https",
#       "--pre-listen-hook", "/abs/path/to/nginx-callback-proxy-hook.sh add",
#       "--post-auth-hook",  "/abs/path/to/nginx-callback-proxy-hook.sh remove"
#     ]
#
# ─── Environment provided by mcp-remote ──────────────────────────────────────
#
#   MCP_REMOTE_HOOK_PHASE             "pre-listen" or "post-auth"
#   MCP_REMOTE_LISTEN_PORT            local port the listener binds to
#   MCP_REMOTE_CALLBACK_PORT          port advertised in the redirect URI
#   MCP_REMOTE_CALLBACK_HOST          hostname advertised in the redirect URI
#   MCP_REMOTE_CALLBACK_SCHEME        http or https
#   MCP_REMOTE_CALLBACK_PATH          callback path (e.g. /mcp/oauth/callback)
#   MCP_REMOTE_CALLBACK_REDIRECT_URI  full redirect URI
#
# ─── Caveat ──────────────────────────────────────────────────────────────────
#
# This removes the proxy rule once the OAuth code is received. If the refresh
# token later becomes invalid, mcp-remote will need to re-run the OAuth flow
# but the rule will be gone. Run mcp-remote again to re-trigger the hooks, or
# leave the rule in place permanently and skip --post-auth-hook.

set -euo pipefail

ACTION="${1:-}"
SNIPPET_DIR="${NGINX_SNIPPET_DIR:-/etc/nginx/snippets}"
RELOAD_CMD="${NGINX_RELOAD:-nginx -s reload}"
SNIPPET_FILE="${SNIPPET_DIR}/mcp-remote-oauth-callback.conf"

case "$ACTION" in
  add)
    : "${MCP_REMOTE_LISTEN_PORT:?must be set by mcp-remote}"
    : "${MCP_REMOTE_CALLBACK_PATH:?must be set by mcp-remote}"

    mkdir -p "$SNIPPET_DIR"
    cat > "$SNIPPET_FILE" <<EOF
# Auto-generated by mcp-remote — do not edit. Will be removed once the OAuth
# flow finishes (when --post-auth-hook fires).
location = ${MCP_REMOTE_CALLBACK_PATH} {
    proxy_pass http://127.0.0.1:${MCP_REMOTE_LISTEN_PORT};
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF
    echo "Wrote $SNIPPET_FILE -> 127.0.0.1:${MCP_REMOTE_LISTEN_PORT}"
    $RELOAD_CMD
    ;;

  remove)
    if [[ -f "$SNIPPET_FILE" ]]; then
      rm -f "$SNIPPET_FILE"
      echo "Removed $SNIPPET_FILE"
      $RELOAD_CMD
    else
      echo "Nothing to remove at $SNIPPET_FILE"
    fi
    ;;

  *)
    echo "Usage: $0 {add|remove}" >&2
    echo "(mcp-remote calls 'add' as --pre-listen-hook and 'remove' as --post-auth-hook)" >&2
    exit 1
    ;;
esac
